version: 2

defaults: &defaults
  docker:
    - image: docker

  working_directory: ~/repo

  steps:
    - checkout
    - setup_remote_docker

    - run:
        command: |
          echo 'Building docker images with tag - $DOCKER_TAG'
    - run:
        command: |
          docker build -t circleciregistry.azurecr.io/someapi:$DOCKER_TAG .
    - run:
        command: |
          docker login --username circleciregistry --password BiM+j6jlBBprE1+nNGZHNWJM5kBtD7Jm circleciregistry.azurecr.io
    - run:
        command: |
          docker push circleciregistry.azurecr.io/someapi:$DOCKER_TAG

jobs:
  build_and_deploy_dev:
    environment:
      DOCKER_TAG: sometag
    <<: *defaults

  build_and_deploy_staging:
    environment:
      DOCKER_TAG: staging
    <<: *defaults

  build_and_deploy_prod:
    environment:
      DOCKER_TAG: production
    <<: *defaults

workflows:
  version: 2
  dev:
    jobs:
      - build_and_deploy_dev:
          filters:
            branches:
              only: develop
  staging:
    jobs:
      - build_and_deploy_staging:
          filters:
            branches:
              only: staging
  prod:
    jobs:
      - build_and_deploy_prod:
          filters:
            branches:
              only: master


















# # Javascript Node CircleCI 2.0 configuration file
# #
# # Check https://circleci.com/docs/2.0/language-javascript/ for more details
# #
# version: 2
# jobs:
#   build:
#     docker:
#       # specify the version you desire here
#       - image: circleci/node:7.10

#     branches: 
#       only:
#         - master
#         - develop
#         - staging

#       # Specify service dependencies here if necessary
#       # CircleCI maintains a library of pre-built images
#       # documented at https://circleci.com/docs/2.0/circleci-images/
#       # - image: circleci/mongo:3.4.4

#     working_directory: ~/repo

#     steps:
#       - checkout

#       # Download and cache dependencies
#       #- restore_cache:
#           # keys:
#             # - v1-dependencies-{{ checksum "package.json" }}
#             # fallback to using the latest cache if no exact match is found
#             # - v1-dependencies-

#       # - run: yarn install

#       # - save_cache:
#       #     paths:
#       #       - node_modules
#       #     key: v1-dependencies-{{ checksum "package.json" }}

#       # run tests!
#       # - run: yarn test

#       - setup_remote_docker

#       - run:
#           command: |
#             echo 'Building docker images with tag - sometag'
#       - run:
#           command: |
#             docker build -t circleciregistry.azurecr.io/someapi:sometag .
#       - run:
#           command: |
#             docker login --username circleciregistry --password BiM+j6jlBBprE1+nNGZHNWJM5kBtD7Jm circleciregistry.azurecr.io
#       - run:
#           command: |
#             docker push circleciregistry.azurecr.io/someapi:sometag
